# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
	config,
	lib,
	# pkgs,
	modulesPath,
	...
}: {
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
	boot.initrd.kernelModules = [];
	boot.kernelModules = ["kvm-amd"];
	boot.extraModulePackages = [];

	# 1TB SSD NVME
	fileSystems."/" = {
		device = "/dev/disk/by-uuid/1077f024-be91-4ac5-9d5b-c4aa00251e15";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/8EC9-010E";
		fsType = "vfat";
		options = ["fmask=0022" "dmask=0022"];
	};
	# 2TB HDD SATA
	fileSystems."/games" = {
		device = "/dev/disk/by-uuid/3F10-2A17";
		fsType = "fat32";
		options = [
			"users" # any user can mount the drive
			"nofail" # dont crash if can't mount
			"exec" # permit to excecute binaries
			"rw"
			# "uid=1000" # id of my user
		];
	};
	# 120 GB SSD SATA
	fileSystems."/ssd" = {
		device = "/dev/disk/by-uuid/468D-FC96";
		fsType = "fat32";
		options = [
			"users" # any user can mount the drive
			"nofail" # dont crash if can't mount
			"exec" # permit to excecute binaries
			"rw"
			# "uid=1000" # id of my user
		];
	};

	swapDevices = [
		{
			device = "/var/lib/swapFile";
			size = 32 * 1024;
		}
	];

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
	# networking.interfaces.wlp34s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
