# standard nvim config, half working, use nixCats instead
{
    pkgs,
    lib,
    config,
    ...
}:
let
    inherit (lib) mkIf mkEnableOption;
    plugins = with pkgs.vimPlugins; [
        lazy-nvim
    ];
in
{
    options = {
        nvim.enable = mkEnableOption {
            default = false;
            description = "enable nvim config";
        };
    };
    config = mkIf config.nvim.enable {

        home.sessionVariables = {
            EDITOR = "nvim";
        };

        # home.packages = with pkgs; [
        # ];
        programs.neovim = {
            enable = true;
            withPython3 = true;
            vimAlias = true;
            defaultEditor = true;
            # plugins
            plugins = plugins;
            # outside dependencies, lsps and formatters
            extraPackages = with pkgs; [
                chafa
                gnumake
                file
            ];
            extraLuaConfig = # lua
                ''
                    -- GENERATED BY NIX
                    -- Make sure to setup `mapleader` before plugins load
                    vim.g.mapleader = " "
                    -- vim.g.maplocalleader = "\\"
                    require("config.options")
                    require("config.keymaps")
                    -- Setup lazy.nvim
                    require("lazy").setup({
                        defaults = {
                            lazy = false,
                            version = false,
                        },
                        -- Configure any other settings here. See the documentation for more details.
                        -- colorscheme that will be used when installing plugins.
                        install = { 
                            -- colorscheme = { "catppuccin" },
                            missing = false, -- dont error out if a package isnt installed by nix
                        },
                        -- automatically check for plugin updates
                        checker = { enabled = true, notify = false },
                        change_detection = { enabled = true, notify = false },
                        performance = {
                            reset_packapth = false,
                            rtp = {
                                disabled_plugins = {},
                                reset = false,
                            },
                        },
                        dev = {
                            path = "${pkgs.vimUtils.packDir config.programs.neovim.finalPackage.passthru.packpathDirs}/pack/myNeovimPackages/start",
                            -- wildcard, specifies that all plugins must use the above path
                            patterns = {""}, 
                        },
                        spec = {
                            -- { import = "plugins.lualine" },
                        },
                    })

                '';
        };

        # links the neovim config into the corrrect directory
        xdg.configFile."nvim/lua" = {
            recursive = true;
            source = ./lua;
        };
    };
}
